apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend-svc
spec:
  type: NodePort
  selector:
    app: task-manager-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080

