apiVersion: v1
kind: Service
metadata:
  name: task-manager-backend-svc
  labels:
    app: task-manager-backend-svc
spec:
  type: ClusterIP
  selector:
    app: task-manager-backend
  ports:
    - port: 8080
      targetPort: 8080
